name: ACP
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=21.2.2
  - python=3.7.11
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==21.2.0
    - backcall==0.2.0
    - bio-transformers==0.1.13
    - biopython==1.79
    - bleach==4.1.0
    - blessings==1.7
    - boto3==1.18.57
    - botocore==1.21.57
    - bravado==11.0.3
    - bravado-core==5.17.0
    - cachetools==4.2.2
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - click==8.0.1
    - colorful==0.5.4
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - fair-esm==0.4.0
    - filelock==3.0.12
    - flatbuffers==1.12
    - fsspec==2021.8.1
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.7
    - gitpython==3.1.24
    - google-api-core==1.31.2
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - gputil==1.4.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - hiredis==2.0.0
    - huggingface-hub==0.0.8
    - idna==3.2
    - importlib-metadata==4.8.1
    - ipykernel==6.4.2
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.2
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonpointer==2.1
    - jsonref==0.2
    - jsonschema==3.2.0
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - monotonic==1.6
    - msgpack==1.0.2
    - multidict==5.1.0
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - neptune-client==0.12.0
    - neptune-tensorflow-keras==0.9.9
    - nest-asyncio==1.5.1
    - notebook==6.4.5
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - opt-einsum==3.3.0
    - packaging==21.0
    - pandas==1.3.2
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.3.2
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - protobuf==3.17.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py-spy==0.3.9
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydeprecate==0.3.1
    - pygments==2.10.0
    - pyjwt==2.2.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytorch-lightning==1.4.5
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - ray==1.6.0
    - redis==3.5.3
    - regex==2021.8.28
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rfc3987==1.3.8
    - rsa==4.7.2
    - s3transfer==0.5.0
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - send2trash==1.8.0
    - simplejson==3.17.5
    - six==1.15.0
    - smmap==4.0.0
    - strict-rfc3339==0.7
    - swagger-spec-validator==2.7.3
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - tokenizers==0.10.3
    - torch==1.8.1
    - torchmetrics==0.4.1
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==5.1.0
    - transformers==4.6.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webcolors==1.11.1
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - yarl==1.6.3
    - zipp==3.5.0

